
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ridha Nadhira Febyan
 */
public class main_frame_uts extends javax.swing.JFrame {

    private String masuk;
    private String keluar;
    
    public main_frame_uts() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nm_ptgs = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        noresi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbmobil = new javax.swing.JRadioButton();
        rbmotor = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nopol = new javax.swing.JTextField();
        tglkeluar = new com.toedter.calendar.JDateChooser();
        tglmasuk = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        RefreshButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama Petugas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 0, 140, 20);
        jPanel1.add(nm_ptgs);
        nm_ptgs.setBounds(20, 20, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("No. Resi");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 50, 140, 20);
        jPanel1.add(noresi);
        noresi.setBounds(20, 70, 160, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis Kendaraan");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 150, 140, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tgl Keluar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 140, 20);

        rbmobil.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(rbmobil);
        rbmobil.setForeground(new java.awt.Color(255, 255, 255));
        rbmobil.setText("Mobil");
        jPanel1.add(rbmobil);
        rbmobil.setBounds(20, 170, 90, 23);

        rbmotor.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(rbmotor);
        rbmotor.setForeground(new java.awt.Color(255, 255, 255));
        rbmotor.setText("Motor");
        jPanel1.add(rbmotor);
        rbmotor.setBounds(120, 170, 90, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Pol");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 100, 140, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tgl Masuk");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 190, 140, 20);
        jPanel1.add(nopol);
        nopol.setBounds(20, 120, 160, 30);
        jPanel1.add(tglkeluar);
        tglkeluar.setBounds(20, 260, 160, 30);
        jPanel1.add(tglmasuk);
        tglmasuk.setBounds(20, 210, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Harga Total (Rp.3000/hari)");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 290, 190, 20);

        harga.setEditable(false);
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel1.add(harga);
        harga.setBounds(20, 310, 160, 30);

        clear.setBackground(new java.awt.Color(153, 153, 255));
        clear.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clear.setText("Clear");
        clear.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(110, 350, 80, 40);

        save.setBackground(new java.awt.Color(153, 153, 255));
        save.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        save.setText("Save");
        save.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(20, 350, 80, 40);

        delete.setBackground(new java.awt.Color(153, 153, 255));
        delete.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        delete.setText("Delete");
        delete.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(20, 400, 80, 40);

        print.setBackground(new java.awt.Color(153, 153, 255));
        print.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        print.setText("Print");
        print.setMargin(new java.awt.Insets(-5, -5, -5, -5));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(110, 400, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 90, 210, 480);

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NmPetugas", "noresi", "nopol", "jenis", "tglmasuk", "tglkeluar", "harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        RefreshButton.setText("Refresh");
        RefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RefreshButton)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(RefreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(210, 90, 530, 480);

        jPanel4.setBackground(new java.awt.Color(0, 0, 204));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PENITIPAN MOBIL DAN MOTOR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 740, 90);

        setBounds(0, 0, 754, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
       SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
       String masuk = dateFormat.format(tglmasuk.getDate());
       String keluar = dateFormat.format(tglkeluar.getDate());
       
       SimpleDateFormat dateFormat2 = new SimpleDateFormat("dd");
       String masuk2 = dateFormat2.format(tglmasuk.getDate());
       String keluar2 = dateFormat2.format(tglkeluar.getDate());
       String JK = "";
       if(rbmobil.isSelected()){
           JK = "Mobil";
       } else {
           JK="Motor";
       }
       //harga.setText()= keluar masuk;
       
       
       int masuk21 = Integer.parseInt(masuk2);
       int keluar21 = Integer.parseInt(keluar2);
       
       int hargaaa = keluar21-masuk21;

       int hargabaru = hargaaa * 3000;
       
       int hargaa = 0;
       if(nm_ptgs.getText().equals("") || noresi.getText().equals("") || nopol.getText().equals("") 
                || JK.equals("") || masuk.equals("")
                || keluar.equals("") ){
            JOptionPane.showMessageDialog(this, "Harap lengkapi data Anda", "Error", JOptionPane.WARNING_MESSAGE);
       }
       else{           
            String SQL = "INSERT INTO tb_main (NmPetugas,noresi,nopol,jenis,tglmasuk,tglkeluar,harga)"
                   +"VALUES('"+nm_ptgs.getText()
                   +"','"+noresi.getText()
                   +"','"+nopol.getText()
                   +"','"+JK+"','"+masuk+"','"+keluar+"','"+hargabaru+"')";
            
            int status = KoneksiDB.execute(SQL);
           
           if(status == 1){
               JOptionPane.showMessageDialog(this,"Data Berhasil Ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
               selectData();
           }else{
               JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
           }
       }
       
        String a = Integer.toString(hargabaru);
        harga.setText(a);
       
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        nm_ptgs.setText("");
        noresi.setText("");
        nopol.setText("");
        tglmasuk.setDate(null);
        tglkeluar.setDate(null);
        harga.setText("");
        buttonGroup1.clearSelection();
        
            }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
       int baris =jTable2.getSelectedRow();
       if(baris != -1){
           String NmPetugas = jTable2.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tb_main WHERE NmPetugas='"+NmPetugas+"'";
           int status = KoneksiDB.execute(SQL);
           if(status ==1)
           {
               JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           }
           else{
               JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       }else
       {
           JOptionPane.showMessageDialog(this,"Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_deleteActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
                                   
        MessageFormat header = new MessageFormat("Penitipan Mobil dan Motor");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)");
            try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH,header,footer,true,null,true,null);
            }catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }    }//GEN-LAST:event_printActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
       
    }//GEN-LAST:event_hargaActionPerformed

    private void RefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshButtonActionPerformed
        selectData();
    }//GEN-LAST:event_RefreshButtonActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
            int baris = jTable2.getSelectedRow();
        if(baris != -1){
            nm_ptgs.setText(jTable2.getValueAt(baris,0).toString());
            noresi.setText(jTable2.getValueAt(baris,1).toString());
            nopol.setText(jTable2.getValueAt(baris,2).toString());
            String JK = jTable2.getValueAt(baris,3).toString();
            if(JK.equals("Mobil")){
                rbmobil.setSelected(true);
            }else
                rbmotor.setSelected(true);
            
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try{
                dateFormat = date.parse(jTable2.getValueAt(baris,4).toString());
            }
            catch(ParseException ex){
                Logger.getLogger(main_frame_uts.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglmasuk.setDate(dateFormat);
            
            Date dateFormat2 = null;
            try{
                dateFormat2 = date.parse(jTable2.getValueAt(baris,5).toString());
            }
            catch(ParseException ex){
                Logger.getLogger(main_frame_uts.class.getName()).log(Level.SEVERE, null, ex);
            }
            tglkeluar.setDate(dateFormat2);
            
            
         
            harga.setText(jTable2.getValueAt(baris,6).toString());
            
            
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
          
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_frame_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_frame_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_frame_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_frame_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_frame_uts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RefreshButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField nm_ptgs;
    private javax.swing.JTextField nopol;
    private javax.swing.JTextField noresi;
    private javax.swing.JButton print;
    private javax.swing.JRadioButton rbmobil;
    private javax.swing.JRadioButton rbmotor;
    private javax.swing.JButton save;
    private com.toedter.calendar.JDateChooser tglkeluar;
    private com.toedter.calendar.JDateChooser tglmasuk;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
    String kolom[] = {"NmPetugas","noresi","nopol","jenis","tglmasuk","tglkeluar","harga"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM tb_main";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()){
                String NmPetugas = rs.getString(1);
                String noresi = rs.getString(2);
                String nopol = rs.getString(3);
                String jenis = "";
                if("Mobil".equals(rs.getString(4))){
                    jenis = "Mobil";
                }else{
                    jenis = "Motor";
                }
                String masuk = rs.getString(5);
                String keluar = rs.getString(6);
                String harga = rs.getString(7);
               // String harga = rs.getString(7);
                String data[] = {NmPetugas,noresi,nopol,jenis,masuk,keluar,harga};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(main_frame_uts.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable2.setModel(dtm);    }
}
